baseurl: "https://www.teamallin.net"
languageCode: "en-us"
title: "Team All In"
enableRobotsTXT: true
params:
  cloudinaryBase: "https://res.cloudinary.com/modii/"
outputs:
  page: ["html", "json"]
  section: ["html", "json"]