baseurl: "https://www.teamallin.net/"
languageCode: "en-us"
title: "Team All In"
enableRobotsTXT: true
params:
  cloudinaryBase: "https://res.cloudinary.com/modii/"
outputs:
  home: ["html", "memberManifest"]
  page: ["html", "json"]
  section: ["html", "json", "repManifest", "RSS"]
outputFormats:
  memberManifest:
    baseName: "manifest"
    isPlainText: true
    mediaType: "application/json"
    permalinkable: true
    notAlternative: true
  repManifest:
    baseName: "manifest"
    isPlainText: true
    mediaType: "application/json"
    permalinkable: true
    notAlternative: true