---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Members Area
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/videos
  label: Videos For Members
  create: documents
  match: "**/*"
  exclude: _index.md
- type: heading
  label: Representative Area
- type: directory
  path: content/representatives/courses
  label: Courses
  create: documents
  match: "**/*"
  templates:
  - course
- type: directory
  path: content/representatives/users
  label: Representatives
  create: documents
  match: "**/*"
  templates:
  - representative
- type: heading
  label: Settings
- type: document
  path: data/site_settings.yaml
  label: Site Settings
  match: "**/*"
upload_dir: team-all-in
public_path: https://res.cloudinary.com/modii/w_800,q_60,f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.2
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.2
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.2
