---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Members Area
- type: document
  path: content/_index.md
  label: Home (Members)
- type: document
  path: content/gallery.md
  label: Photo Gallery
- type: document
  path: content/member-resources.md
  label: Videos For Members
- type: document
  path: content/apps-to-download.md
  label: App Page
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - blog-post
- type: heading
  label: Representative Area
- type: document
  path: content/representatives/_index.md
  label: Home (Reps)
- type: document
  path: content/representatives/leader-videos.md
  label: Leader Videos
- type: document
  path: content/representatives/courses/_index.md
  label: Course List Page
- type: directory
  path: content/representatives/courses
  label: Courses
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - course
- type: directory
  path: content/users
  label: Users
  create: documents
  match: "**/*"
  templates:
  - representative
- type: heading
  label: Marketing Content
- type: directory
  path: content/ev
  label: Email Videos
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - email-video
- type: heading
  label: Settings
- type: document
  path: data/site_settings.yaml
  label: Site Settings
- type: document
  path: content/blog/_index.md
  label: Blog Settings
upload_dir: team-all-in
public_path: https://res.cloudinary.com/modii/w_800,q_60,f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.55.6
  - HUGO_ENV=staging
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:node10
  mount_path: "/srv"
  instant_preview_command: hugo server -D -F -E --renderToDisk --port 8080 --bind
    0.0.0.0
version: 0.55.2
