---
label: Site Settings
hide_body: true
fields:
- name: branding
  type: field_group
  config: {}
  label: Branding
  fields:
  - name: logo
    type: file
    config:
      maxSize: 250
    label: Logo
  - name: favicon
    type: file
    config:
      maxSize: 250
    label: Favicon
