---
label: Site Settings
hide_body: true
fields:
- name: branding
  type: field_group
  config: {}
  label: Branding
  fields:
  - name: logo
    type: file
    config:
      maxSize: 250
    label: Logo
  - name: favicon
    type: file
    config:
      maxSize: 250
    label: Favicon
- name: contact_info
  type: field_group
  config: {}
  fields:
  - name: contact_name
    type: text
    config:
      required: false
    label: Contact Name
  - name: email
    type: text
    config:
      required: false
    label: Email
  - name: phone_number
    type: text
    config:
      required: false
    label: Phone Number
  label: Contact Info
- name: representatives
  type: field_group
  config: {}
  fields:
  - name: user_profile_message
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: markdown
    label: User Profile Message
    description: Message that appears on the users profile
  label: Representative Area
pages:
- data/site_settings.yaml
